### ISSUE TITLE
Need Samples for Web API

### ISSUE THREAD

**Issue by mdumanoj** [Azure-Samples/Cognitive-Speech-STT-ServiceLibrary#11]
Need Samples for Web API. To upload the Audio file and convert that into Text. I tried out this example but I am not getting any response. But Desktop Client is working fine, printing transcript in the command line. It would be great If there is some more examples.

**Comment by zhouwangzw** [comment]
The sample in the `sample`  folder works for me. You need to provide the following arguments when running the application, as described [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedcsharpservicelibrary).
  - Arg[0]: Specify an input audio WAV file.
  - Arg[1]: Specify the audio locale.
  - Arg[2]: Specify the recognition modes: Short for the ShortPhrase mode and Long for the LongDictation mode.
  - Arg[3]: Specify the subscription key to access the speech recognition service.

**Comment by mdumanoj** [comment]
Yes. I can also run this code in Console Mode. But I want to develop a Web API which gets the file from post request and process the file to convert into Text. I am not getting any response there. Any help?

**Comment by zhouwangzw** [comment]
The sample program shows key steps how to interact with the SDK and the service. If the sample works for you, it means you can correctly talk to the speech service using the SDK. However, we do not know how your application is using the SDK. Have you checked whether any step is missing? What do you mean by "not getting any response"? Have you used Fiddler to check whether any requests have been sent to the speech service and what are the responses from the service? Is your application waiting for the recognition result?

**Comment by mdumanoj** [comment]
I Created my application as a Web API, I am using this SDK in that. There I have one API which gets the audio file in the request and converts that file into text, prints that in Debug Statement. Here my Code is just waiting for Response Forever. Is there any additional configuration has to be done for Web API?

**Comment by zhouwangzw** [comment]
@mdumanoj Have you used Fiddler to check whether any request is sent to the service? And any event handler OnPartialResult or OnRecognitionResult has been called in your application? The recognition respose is recevied from those event handlers.

**Comment by mdumanoj** [comment]
Hey thank you for your help @zhouwangzw. 

I just changed this line from `this.Run(destinationPath, Locale, LongDictationUrl, SubscriptionKey).Wait();` to `await this.Run(destinationPath, Locale, LongDictationUrl, SubscriptionKey);`

Now I'm getting response in the Event Handler. Once again thank you so much for your prompt response and Appreciate it.
