### ISSUE TITLE
How to increase Intial silence timeout

### ISSUE THREAD

**Issue by ekajune18** [Azure-Samples/Cognitive-Speech-STT-ServiceLibrary#6]
Im trying to use STT serviceLibrary for transcribing call center audio file which most of them contain the call connection sound for the first few second. 
everytime try to transcribe the audio, the response from phrase recognition result is always "initial silence timeout". I realize the time limit for "initial timeout" is about 15 sec long. however, if the audio contain a conversation sound start from the 16 sec till the end, I expect the speech recognition keep sending the request to the speech service untill last sec of the audio instead of stopping the process and give the initial silence timeout result.
My question is, can I change the initial silence timeout using SpeechClient API, because i cannot find any property that I can use for assigning the initial silence timeout?

**Comment by priyaravi20** [comment]
Sorry for the delay in response. THis is not configurable at the present moment. We are working to enable a continous recognition when there are no timeouts in the next few months.

**Comment by 1Click1Life** [comment]
Hello priyaravi20 ... is there an update on this .... I would really like to be able to control the timeout. Thanks
